# Change these first
owner: northwest-media-inland # Your GitHub organization or username, where this repository lives
repo: nwm-upptime # The name of this repository

sites:
  - name: 208rvpark.com
    url: https://208rvpark.com
  - name: northwest.media
    url: https://northwest.media
  - name: a1mobilewelder.com
    url: https://a1mobilewelder.com
  - name: a-rconst.com
    url: https://a-rconst.com
  - name: a1mobilewelder.com
    url: https://a1mobilewelder.com
  - name: aeraexcavation.com
    url: https://aeraexcavation.com
  - name: airportrentaspacellc.com
    url: https://airportrentaspacellc.com
  - name: animalclinic.org
    url: https://animalclinic.org
  - name: apetparlorofwa.com
    url: https://apetparlorofwa.com
  - name: arnzenconstruction.com
    url: https://arnzenconstruction.com
  - name: artbeatinc.com
    url: https://artbeatinc.com
  - name: asotincountyregionallandfill.com
    url: https://asotincountyregionallandfill.com
  - name: asotincountystormwater.com
    url: https://asotincountystormwater.com 
  - name: bandbpools.net
    url: https://bandbpools.net
  - name: beacon-christian.org
    url: https://beacon-christian.org
  - name: beanmarinefabrication.com
    url: https://beanmarinefabrication.com
  - name: bearabledentistry.com 
    url: https://bearabledentistry.com
  - name: bestbuiltbuilderssupply.com 	
    url: https://bestbuiltbuilderssupply.com
  - name: bleedred.com
    url: https://bleedred.com
  - name: blpi.com
    url: https://blpi.com
  - name: blueribbonlinen.com
    url: https://blueribbonlinen.com
  - name: bonebrakeconstruction.com
    url: https://bonebrakeconstruction.com
  - name: borderline-lighting.com
    url: https://borderline-lighting.com
  - name: borderlinerivercharters.com
    url: https://borderlinerivercharters.com
  - name: bravaslewiston.com
    url: https://bravaslewiston.com
  - name: buildingblockspt.com
    url: https://buildingblockspt.com
  - name: burlingamemachine.com
    url: https://burlingamemachine.com
  - name: calamshriners.com
    url: https://calamshriners.com
  - name: cambio.design
    url: https://cambio.design
  - name: candbmusic.com
    url: https://candbmusic.com
  - name: cap4action.org
    url: https://cap4action.org
  - name: castillodefeliciana.com
    url: https://castillodefeliciana.com
  - name: cityofgenesee.com
    url: https://cityofgenesee.com
  - name: clarkandfeeney.com
    url: https://clarkandfeeney.com
  - name: clarkston-wa.com
    url: https://clarkston-wa.com
  - name: clarkstoneducationfoundation.org
    url: https://clarkstoneducationfoundation.org
  - name: clearwatercanyoncellars.com
    url: https://clearwatercanyoncellars.com
  - name: clearwaterfarms.us
    url: https://clearwaterfarms.us
  - name: cookscarco.com
    url: https://cookscarco.com
  - name: costasautorepair.com
    url: https://costasautorepair.com
  - name: covermetees.com
    url: https://covermetees.com/
  - name: crsupplements.com 	
    url: https://crsupplements.com
  - name: davesgolfonline.com
    url: https://davesgolfonline.com
  - name: daytonlodge.com
    url: https://daytonlodge.com
  - name: debcousa.com
    url: https://debcousa.com
  - name: dicksonreadymix.com
    url: https://dicksonreadymix.com
  - name: dkmullin.com
    url: https://dkmullin.com
  - name: doublebarrelexpress.com
    url: https://doublebarrelexpress.com
  - name: douglasslawfirm.net
    url: https://douglasslawfirm.net
  - name: dropforgeleathercare.com
    url: https://dropforgeleathercare.com
  - name: dropforgewoodcare.com
    url: https://dropforgewoodcare.com
  - name: dyehardllc.com
    url: https://dyehardllc.com
  - name: ecmxpark.com
    url: https://ecmxpark.com
  - name: evergem.com
    url: https://evergem.com
  - name: everybody-reads.org
    url: https://everybody-reads.org
  - name: fishersystems.com
    url: https://fishersystems.com
  - name: forum.hotwiredirect.com
    url: https://forum.hotwiredirect.com
  - name: framedbykane.com
    url: https://framedbykane.com
  - name: framewrk.us
    url: https://framewrk.us
  - name: fritzprecisionshooting.com
    url: https://fritzprecisionshooting.com
  - name: garfieldcta.com
    url: https://garfieldcta.com
  - name: gateway-materials.com
    url: https://gateway-materials.com
  - name: gatewaycustomdecking.com
    url: https://gatewaycustomdecking.com
  - name: gatewaywinchester.com
    url: https://gatewaywinchester.com
  - name: gid-mt.org
    url: https://gid-mt.org
  - name: golflgcc.com	
    url: https://golflgcc.com
  - name: golfscoring.com
    url: https://golfscoring.com
  - name: golws.com
    url: https://golws.com
  - name: greco-construction.com
    url: https://greco-construction.com
  - name: greenshirts.net
    url: https://greenshirts.net
  - name: hayeshouseclarkston.com
    url: https://hayeshouseclarkston.com
  - name: hellscanyonapparel.com
    url: https://hellscanyonapparel.com
  - name: helpinghandsrescue.org
    url: https://helpinghandsrescue.org
  - name: hermistontrailers.com
    url: https://hermistontrailers.com
  - name: holyfamilyclarkston.com
    url: https://holyfamilyclarkston.com
  - name: homesatcanyoncrest.com
    url: https://homesatcanyoncrest.com
  - name: hotwiredirect.com
    url: https://hotwiredirect.com
  - name: hudsonslandscaping.com
    url: https://hudsonslandscaping.com
  - name: iclowdown.com
    url: https://iclowdown.com
  - name: idahofirewise.org
    url: https://idahofirewise.org
  - name: idahotrucksales.com
    url: https://idahotrucksales.com
  - name: imiproperties.com
    url: https://imiproperties.com
  - name: improvelivingston.com
    url: https://improvelivingston.com
  - name: imualcv.com
    url: https://imualcv.com
  - name: inlandcell.com
    url: inlandcell.com
  - name: intermountainfeed.com
    url: https://intermountainfeed.com
  - name: jacksonspayitforward.com
    url: https://jacksonspayitforward.com
  - name: javastopespresso.com
    url: https://javastopespresso.com
  - name: jrass.net
    url: https://jrass.net
  - name: jrussellexcavation.com	
    url: https://jrussellexcavation.com
  - name: justbreatherdh.com
    url: https://justbreatherdh.com
  - name: kandgconstructionllc.com
    url: https://kandgconstructionllc.com
  - name: kingsthrones.com
    url: https://kingsthrones.com
  - name: larsoncabinetcompany.com
    url: https://larsoncabinetcompany.com
  - name: lccrew.com
    url: https://lccrew.com
  - name: lctheatre.org
    url: https://lctheatre.org
  - name: lcvalleyconcrete.com
    url: https://lcvalleyconcrete.com
  - name: lcvfootball.com
    url: https://lcvfootball.com
  - name: legaljive.com
    url: https://legaljive.com
  - name: lewisclarkgihealth.com
    url: https://lewisclarkgihealth.com
  - name: lewisclarkwine.com
    url: https://lewisclarkwine.com
  - name: lewistonbailbonds.com
    url: https://lewistonbailbonds.com
  - name: lewistonbrewfest.com
    url: https://lewistonbrewfest.com
  - name: lewistoncurbing.com
    url: https://lewistoncurbing.com
  - name: lewistonidaholittleleague.com
    url: https://lewistonidaholittleleague.com
  - name: lewistonlibraryfoundation.org
    url: https://lewistonlibraryfoundation.org
  - name: lewistonroundup.com
    url: https://lewistonroundup.com
  - name: lewistonrv.com
    url: https://lewistonrv.com
  - name: livingwaterslawnandlandscape.com
    url: https://livingwaterslawnandlandscape.com
  - name: lorimccannforidaho.com
    url: https://lorimccannforidaho.com
  - name: lowdown.weistowers.com
    url: https://lowdown.weistowers.com
  - name: lucasmartindrywallllc.com
    url: https://lucasmartindrywallllc.com
  - name: markofthefaerie.com 
    url: https://markofthefaerie.com
  - name: martiebeck.com 	
    url: https://martiebeck.com
  - name: mastersbodyworksinc.com
    url: https://mastersbodyworksinc.com
  - name: mccannredangus.com
    url: https://mccannredangus.com
  - name: michaelkellyblues.com
    url: https://michaelkellyblues.com
  - name: michaellimner.com
    url: https://michaellimner.com
  - name: moscowautomotive.com
    url: https://moscowautomotive.com
  - name: moscowura.com
    url: https://moscowura.com
  - name: myhealthyfunction.com
    url: https://myhealthyfunction.com
  - name: naiaworldseries.com
    url: https://naiaworldseries.com
  - name: nelsoncomfortsolutions.com
    url: https://nelsoncomfortsolutions.com
  - name: newsomecabin.com
    url: https://newsomecabin.com
  - name: northwestcoaster.com
    url: https://northwestcoaster.com
  - name: nwengraving.com
    url: https://nwengraving.com
  - name: nwtees.com
    url: https://nwtees.com
  - name: onlyraindownthedrain.com
    url: https://onlyraindownthedrain.com
  - name: oui.org
    url: https://oui.org
  - name: parejascellars.com
    url: https://parejascellars.com
  - name: portofclarkston.com
    url: https://portofclarkston.com
  - name: portoflewiston.com
    url: https://portoflewiston.com
  - name: precision-signs.com
    url: https://precision-signs.com
  - name: propropertylcv.com
    url: https://propropertylcv.com
  - name: qbhs.org
    url: https://qbhs.org
  - name: qpins.net
    url: https://qpins.net
  - name: quiettigertaichi.com
    url: https://quiettigertaichi.com
  - name: radmulching.com
    url: https://radmulching.com
  - name: rdelectric.org
    url: https://rdelectric.org
  - name: reveulogy.com
    url: https://reveulogy.com
  - name: ridethevalley.org
    url: https://ridethevalley.org
  - name: rivercityespresso.com
    url: https://rivercityespresso.com
  - name: riverpointedevelopment.com
    url: https://riverpointedevelopment.com
  - name: rousseauco.com
    url: https://rousseauco.com
  - name: rumina.com
    url: https://rumina.com/
  - name: sandcastlekidsdaycare.com
    url: https://sandcastlekidsdaycare.com
  - name: shattuckcreek.com
    url: https://shattuckcreek.com
  - name: shotoutclothing.com
    url: https://shotoutclothing.com
  - name: signcraftersinc.net
    url: https://signcraftersinc.net
  - name: simmons-nadl.com
    url: https://simmons-nadl.com
  - name: skalickysbakery.com
    url: https://skalickysbakery.com
  - name: snakeriverboats.com
    url: https://snakeriverboats.com
  - name: srccfreeclinic.org
    url: https://srccfreeclinic.org
  - name: station3clarkston.com
    url: https://station3clarkston.com
  - name: stonebrakermcquary.com
    url: https://stonebrakermcquary.com
  - name: suttonsalvage.com
    url: https://suttonsalvage.com
  - name: tarasstitches.com
    url: https://tarasstitches.com
  - name: tcuw.org
    url: https://tcuw.org
  - name: tdhengineering.com
    url: https://tdhengineering.com
  - name: theaquaticcenter.org
    url: https://theaquaticcenter.org
  - name: thebarnatmaderfarm.com
    url: https://thebarnatmaderfarm.com
  - name: thenezperceway.org
    url: https://thenezperceway.org
  - name: uniontownwa.org
    url: https://uniontownwa.org
  - name: upthecreekhvac.com
    url: https://upthecreekhvac.com
  - name: us95thorncreek.com
    url: https://us95thorncreek.com
  - name: vpacci.com
    url: https://vpacci.com
  - name: wallawallatrailers.com
    url: https://wallawallatrailers.com
  - name: wdmsstore.com
    url: https://wdmsstore.com
  - name: westernfloorslewiston.com
    url: https://westernfloorslewiston.com
  - name: williamsphc.com
    url: https://williamsphc.com
  - name: willow-center.org
    url: https://willow-center.org
  - name: winchesterkitchenandbar.com
    url: https://winchesterkitchenandbar.com
  - name: windfall.design
    url: https://windfall.design
  - name: wwmillcreekmechanical.com
    url: https://wwmillcreekmechanical.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.northwest.media
  # baseUrl: /nwm-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** For Northwest Media Websites"
  introMessage: Status of Client Sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
